---
name: Bug report
description: Create a report to help us improve MacVim.
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting issues of MacVim!

        If you want to report a security issue, instead of reporting it here publicly, please disclose it using the steps listed at https://github.com/macvim-dev/macvim/security/policy.

        For general Vim issues that are not specific to MacVim, please file them at https://github.com/vim/vim.
        
        To make it easier for us to help you please enter detailed information below.
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    attributes:
      label: Version of MacVim
      description: >
        MacVim release number (e.g. r181). Use "About MacVim" to find out which one you are using. If building manually from source, provide the Git commit hash instead (e.g. a4466fe3b695).
    validations:
      required: true
  - type: input
    attributes:
      label: MacVim installation method
      description: >
        Was MacVim downloaded from GitHub release, installed via Homebrew / Homebrew Cask / MacPorts, or built from source manually?
  - type: textarea
    attributes:
      label: Environment
      description: >
        macOS version (e.g. macOS 15.3.2 Sequoia), Mac type (e.g. MacBook Air M2), terminal (e.g. Apple Terminal/iTerm); anything that might matter
      placeholder: |
        macOS version:
        Mac:
        Terminal:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs and stack traces
      placeholder: Insert log or other text here (if necessary)
      render: shell
  - type: textarea
    attributes:
      label: Vim and MacVim configuration where issue is reproducable
      description: Provide a link to vimrc and/or MacVim settings (see https://github.com/macvim-dev/macvim/wiki/Reporting-an-Issue for how to obtain it).
  - type: checkboxes
    attributes:
      label: How was MacVim launched?
      description: Different ways of opening MacVim can have an impact on the behavior.
      options:
        - label: by launching MacVim.app in macOS (by using the Dock, Spotlight, or the `open` command)
        - label: by running mvim/gvim in the terminal
  - type: checkboxes
    attributes:
      label: Issue has been tested with clean configuration
      description: Running MacVim and Vim with clean configurations allow us to narrow down whether this is a configuration issue.
      options:
        - label: by running `mvim --clean` (or `gvim`, supplied by MacVim distribution). You can also use the File → "New Clean Window" menu item within MacVim.
        - label: by running `vim --clean` (in terminal, supplied by MacVim distribution)
        - label: by running `vim --clean` (in terminal, other suppliers, e.g. /usr/bin/vim)
